# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/TEST_BD/TEST_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_BD || ORIG_REF_NAME==TEST_BD} -quiet] -quiet

# IP: bd/TEST_BD/ip/TEST_BD_processing_system7_0_0/TEST_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_BD_processing_system7_0_0 || ORIG_REF_NAME==TEST_BD_processing_system7_0_0} -quiet] -quiet

# XDC: bd/TEST_BD/TEST_BD_ooc.xdc
